import { trans } from '../utils';

const CONSTANTS = {
  ALPHA_NUMERIC_REGEX: /^([a-zA-Z0-9]|[ ])+$/,
  SPL_CHAR_REGEX: /^[a-zA-Z0-9 ,.\-/"\\()<>!]*$/,
  ALPHA_REGEX: /^([A-Za-z]|[ ])+$/,
  EMAIL_REGEX: /^[a-zA-Z0-9._-]+@[a-zA-Z0-9]+\.+[a-zA-Z]+$/,
  BAR_GRAPH_COLOR: '#eef7f4',
  BAR_GRAPH_HOVER_COLOR: '#d4eae4',
  // margin from center of doughnut x-axis
  DOUGHNUT_CHART_XAXIS_CENTER: 21,
  DOUGHNUT_COLOR_CHART: [ "#007fa3", "#12b2a6", "#84bd00", "#9e007e", "#ffb81c", "#ea7600" ],
  DOUGHNUT_DEFAULT_COLOR: [ "#e5e5e5" ],
  GRAPH_DEFAULT_LABELS: () => [ trans('Reading'), trans('Listening'), trans('Writing'), trans('Speaking'), trans('Grammar'), trans('Vocabulary') ],
  STACK_BAR_SOCIAL_COLOR: '#ea7600',
  STACK_BAR_SOCIAL_HOVER_COLOR: '#f4ba7f',
  STACK_BAR_PRO_COLOR: '#ffb81c',
  STACK_BAR_PRO_HOVER_COLOR: '#ffdb8d',
  FLASH_MESSAGE_DURATION: 5000,
  LANGUAGES: { 'en': 'English' },
  PASSING_SCORE: 70,
  SLIDER_INTERVAL: 3000,
  SUCCESS_MESSAGE: trans('All changes saved successfully'),
  TRANSLATION_URL: `${window.location.origin}/s3.json`,
  CIRCLE_CHART_TEXT_COLOR_1: '#007fa3',
  CIRCLE_CHART_TEXT_COLOR_2: '#c44724',
  CIRCLE_CHART_TEXT_COLOR_3: '#12b2a6',
  CIRCLE_CHART_TEXT_COLOR_4: '#ffb81c',
  CIRCLE_CHART_TEXT_COLOR_5: '#ea7600',
  CIRCLE_CHART_TEXT_COLOR_6: '#4e4e4e',
  CIRCLE_CHART_PATH_STROKE_COLOR_1: '#007fa3',
  CIRCLE_CHART_PATH_STROKE_COLOR_2: '#c44724',
  CIRCLE_CHART_PATH_STROKE_COLOR_3: '#12b2a6',
  CIRCLE_CHART_PATH_STROKE_COLOR_4: '#ffb81c',
  CIRCLE_CHART_PATH_STROKE_COLOR_5: '#ea7600',
  INSTITUTES_LIST_TITLES: [ trans('INSTITUTES'), trans('MASTER LEARNERS') ],
  LEARNER_LIST_TITLES: [ trans('NAME'), trans('LOGIN ID') ],
  RECORD_PER_PAGE: 10,
  ERROR_MESSAGE: () => trans('Something went wrong'),
  assetTypeInvalid: (ContentType) => `${ContentType} ${trans('not supported')}`,
  PRODUCT_IDENTIFIER: "OAEPProductTestIN0101",
  LEARNER_PRODUCT_IDENTIFIER: "oaepProductTest1",
  LEARNER_COURSE_ID: "5dd37923e1d6e30011b7fb3b",
  USER_TYPE: "MASTER",
  IFRAME_AUTHTYPE: "pulse",
  IFRAME_SCROM_CONTENTTYPE: "scorm",
  IFRAME_HTM_CONTENTTYPE: "htm",
  htmToken: "00777cbb-7e20-4db6-878e-7f6730132ce8"
};

export default CONSTANTS;
